/**
 * seedTeamMembers.js
 * 
 * Non-destructive, idempotent seed script for the SCIEnT team.
 * Uses findOneAndUpdate({ name, role, year }, { $set: member }, { upsert: true })
 * so running multiple times safely updates or inserts without creating duplicates.
 * 
 * Run from server/ directory:
 *   node scripts/seedTeamMembers.js
 */
require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const mongoose = require('mongoose');
const connectDB = require('../config/db');
const TeamMember = require('../models/TeamMember');

const realTeamMembers = [
  {
    "name": "Dr. A. K. Bakthavatsalam",
    "role": "Faculty Advisor",
    "subteam": null,
    "Department": "Energy & Environment Engineering",
    "photoUrl": "/Team/Dr_A_K_Bakthavatsalam.png",
    "email": "baktha@nitt.edu",
    "linkedin": "https://www.linkedin.com/company/scientnitt/",
    "instagram": "",
    "description": "Guiding innovation and research initiatives in engineering and technology",
    "year": null,
    "order": 1,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Mr. Sivanesan S",
    "role": "Admin Executive",
    "subteam": null,
    "Department": "SCIEnT Facility Operations",
    "photoUrl": "/Team/Sivaneshan.jpg",
    "email": "sivaneshan@nitt.edu",
    "linkedin": "https://www.linkedin.com/company/scientnitt/",
    "instagram": "",
    "description": "Overseeing facility management and operational excellence at SCIEnT",
    "year": null,
    "order": 2,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Dr. -Ing Prince Gideon Kubendran Amos",
    "role": "Faculty Advisor",
    "subteam": null,
    "Department": "Metallurgical and Materials Engineering",
    "photoUrl": "https://www.nitt.edu/home/academics/departments/meta/faculty/prince/Prince200x238.jpg",
    "email": "prince@nitt.edu",
    "linkedin": "https://nitt.irins.org/profile/214573",
    "instagram": "",
    "description": "Assistant Professor, Dept. of Metallurgical and Materials Engineering, NIT Trichy. Ph.D. from Karlsruhe Institute of Technology (magna cum laude).",
    "year": null,
    "order": 3,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Arjun B K",
    "role": "Technical Executive",
    "subteam": "Cores",
    "Department": "EEE",
    "photoUrl": null,
    "email": "arjunbharathikumar@gmail.com",
    "linkedin": "https://www.linkedin.com/company/scientnitt/",
    "instagram": "https://www.instagram.com/scient_nitt/",
    "description": "Leading key initiatives in the student team",
    "year": "25-26",
    "order": 3,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Alok Verma",
    "role": "Facility Executive",
    "subteam": "Cores",
    "Department": "MECH",
    "photoUrl": null,
    "email": "alokverma4237@gmail.com",
    "linkedin": "https://www.linkedin.com/company/scientnitt/",
    "instagram": "https://www.instagram.com/scient_nitt/",
    "description": "Contributing to team leadership and projects",
    "year": "25-26",
    "order": 4,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Srinath Nagarajan",
    "role": "Project Operations Executive",
    "subteam": "Cores",
    "Department": "ICE",
    "photoUrl": null,
    "email": "nsrinath2401@gmail.com",
    "linkedin": "https://www.linkedin.com/in/srinath-nagarajan",
    "instagram": "https://www.instagram.com/wtfsrinath/",
    "description": "Overseeing project operations and execution",
    "year": "25-26",
    "order": 54,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Alan Prakash",
    "role": "External Affairs Executive",
    "subteam": "Cores",
    "Department": "CIVIL",
    "photoUrl": null,
    "email": "alanprakash55@gmail.com",
    "linkedin": "https://www.linkedin.com/company/scientnitt/",
    "instagram": "https://www.instagram.com/scient_nitt/",
    "description": "Driving technical and organizational efforts",
    "year": "25-26",
    "order": 5,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Mahalakshmi R",
    "role": "Internal Affairs Executive",
    "subteam": "Cores",
    "Department": "MME",
    "photoUrl": null,
    "email": "mahalakshmi0ramesh@gmail.com",
    "linkedin": "https://www.linkedin.com/company/scientnitt/",
    "instagram": "https://www.instagram.com/scient_nitt/",
    "description": "Coordinating team activities and outreach",
    "year": "25-26",
    "order": 6,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Advaith S",
    "role": "Manager",
    "subteam": "DevOps",
    "Department": "CSE",
    "photoUrl": null,
    "email": "advaith.t20@gmail.com",
    "linkedin": "https://www.linkedin.com/in/advaith-s-35692a2ab/",
    "instagram": "https://www.instagram.com/advaith.fyi/",
    "description": "Leading DevOps initiatives and technical projects",
    "year": "25-26",
    "order": 7,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Dendukuri Soumya",
    "role": "Manager",
    "subteam": "Corporate Communications",
    "Department": "CIVIL",
    "photoUrl": null,
    "email": "soumya95507@gmail.com",
    "linkedin": "https://www.linkedin.com/company/scientnitt/",
    "instagram": "https://www.instagram.com/scient_nitt/",
    "description": "Coordinating corporate communications and outreach",
    "year": "25-26",
    "order": 8,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Divyansh Kumar Agrawal",
    "role": "Manager",
    "subteam": "DevOps",
    "Department": "CSE",
    "photoUrl": null,
    "email": "divyanshkumaragrawal80@gmail.com",
    "linkedin": "https://www.linkedin.com/in/divyansh-agrawal-4a806a2b1",
    "instagram": "https://www.instagram.com/divyansh_agr_80",
    "description": "Driving DevOps solutions and technical development",
    "year": "25-26",
    "order": 9,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Gargi Gupta",
    "role": "Manager",
    "subteam": "Corporate Communications",
    "Department": "MECH",
    "photoUrl": null,
    "email": "gargi.gupta0601@gmail.com",
    "linkedin": "https://www.linkedin.com/company/scientnitt/",
    "instagram": "https://www.instagram.com/scient_nitt/",
    "description": "Managing corporate communications and events",
    "year": "25-26",
    "order": 10,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Indhumathi V",
    "role": "Manager",
    "subteam": "DevOps",
    "Department": "PROD",
    "photoUrl": null,
    "email": "indhu23.v@gmail.com",
    "linkedin": "https://www.linkedin.com/company/scientnitt/",
    "instagram": "https://www.instagram.com/scient_nitt/",
    "description": "Enhancing team outreach through communications",
    "year": "25-26",
    "order": 11,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Kakularam Saiprakash Reddy",
    "role": "Manager",
    "subteam": "DevOps",
    "Department": "CIVIL",
    "photoUrl": null,
    "email": "kakularamsaiprakashreddy9@gmail.com",
    "linkedin": "https://www.linkedin.com/in/sai-prakash-reddy-kakularam-323273280/",
    "instagram": "https://www.instagram.com/saiprakashreddy.k/",
    "description": "Contributing to DevOps and technical innovation",
    "year": "25-26",
    "order": 12,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Mona M S",
    "role": "Manager",
    "subteam": "Corporate Communications",
    "Department": "MME",
    "photoUrl": null,
    "email": "mona.shivakkumar@gmail.com",
    "linkedin": "https://www.linkedin.com/in/mona-m-s-10228b300",
    "instagram": "https://www.instagram.com/_.mona._.01._/",
    "description": "Leading corporate communication strategies",
    "year": "25-26",
    "order": 13,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Pranesh S K",
    "role": "Manager",
    "subteam": "Creatives",
    "Department": "MME",
    "photoUrl": null,
    "email": "pranesh26erd@gmail.com",
    "linkedin": "https://www.linkedin.com/company/scientnitt/",
    "instagram": "https://www.instagram.com/scient_nitt/",
    "description": "Coordinating team communications and events",
    "year": "25-26",
    "order": 14,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Shivam Mishra",
    "role": "Manager",
    "subteam": "DevOps",
    "Department": "ICE",
    "photoUrl": null,
    "email": "realshivat2606@gmail.com",
    "linkedin": "https://www.linkedin.com/company/scientnitt/",
    "instagram": "https://www.instagram.com/scient_nitt/",
    "description": "Supporting DevOps projects and technical tasks",
    "year": "25-26",
    "order": 15,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Tanisha Narasimman",
    "role": "Manager",
    "subteam": "Corporate Communications",
    "Department": "MME",
    "photoUrl": null,
    "email": "tanishanarasimman777@gmail.com",
    "linkedin": "https://www.linkedin.com/company/scientnitt/",
    "instagram": "https://www.instagram.com/scient_nitt/",
    "description": "Promoting team initiatives through communications",
    "year": "25-26",
    "order": 16,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Vedavarshini",
    "role": "Manager",
    "subteam": "Creatives",
    "Department": "EEE",
    "photoUrl": null,
    "email": "vedavarshiniv2@gmail.com",
    "linkedin": "https://www.linkedin.com/company/scientnitt/",
    "instagram": "https://www.instagram.com/scient_nitt/",
    "description": "Crafting creative visuals for team projects",
    "year": "25-26",
    "order": 17,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Thejashvee",
    "role": "Manager",
    "subteam": "Corporate Communications",
    "Department": "ICE",
    "photoUrl": null,
    "email": "thejubabu1@gmail.com",
    "linkedin": "https://www.linkedin.com/company/scientnitt/",
    "instagram": "https://www.instagram.com/scient_nitt/",
    "description": "Enhancing team visibility through communications",
    "year": "25-26",
    "order": 18,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Sanskar Sharma",
    "role": "Deputy Manager",
    "subteam": "DevOps",
    "Department": "CSE",
    "photoUrl": null,
    "email": "sharmasanskar7201@gmail.com",
    "linkedin": "https://www.linkedin.com/in/sanskar-sharma-0515a9319",
    "instagram": "https://www.instagram.com/_sekhar_sharma/",
    "description": "Contributing to DevOps and technical tasks",
    "year": "25-26",
    "order": 19,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Hasini Thakkallapelly",
    "role": "Deputy Manager",
    "subteam": "Corporate Communications",
    "Department": "CSE",
    "photoUrl": null,
    "email": "hasini.thakkallapelly34@gmail.com",
    "linkedin": "https://www.linkedin.com/in/hasinithakkallapelly/",
    "instagram": "https://www.instagram.com/hasini_rufg/",
    "description": "Assisting in corporate communications",
    "year": "25-26",
    "order": 20,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "S. Nayan Vamsi",
    "role": "Deputy Manager",
    "subteam": "DevOps",
    "Department": "CSE",
    "photoUrl": null,
    "email": "nayanvamsi@gmail.com",
    "linkedin": "https://www.linkedin.com/in/nayan-vamsi-sunkarapalli-b2a93536b/",
    "instagram": "https://www.instagram.com/___nayan__007/",
    "description": "Contributing to DevOps and technical development",
    "year": "25-26",
    "order": 21,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Kamalakannan Ravichandran",
    "role": "Deputy Manager",
    "subteam": "Corporate Communications",
    "Department": "CIVIL",
    "photoUrl": null,
    "email": "kamalakannanravichandran@gmail.com",
    "linkedin": "https://www.linkedin.com/in/kamalakannan-ravichandran-843b662a5",
    "instagram": "https://www.instagram.com/kamalakannanravichandran11",
    "description": "Supporting corporate communications efforts",
    "year": "25-26",
    "order": 22,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Chebrolu Bhuvan",
    "role": "Deputy Manager",
    "subteam": "DevOps",
    "Department": "CSE",
    "photoUrl": null,
    "email": "bhuvanchebrolu@gmail.com",
    "linkedin": "https://www.linkedin.com/in/bhuvan-chebrolu-5835641b2/",
    "instagram": "https://www.instagram.com/bhuvaneshwar2966/",
    "description": "Assisting in DevOps projects and technical tasks",
    "year": "25-26",
    "order": 23,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "S. Janani Krithika",
    "role": "Deputy Manager",
    "subteam": "Corporate Communications",
    "Department": "CIVIL",
    "photoUrl": null,
    "email": "jananikrithika9@gmail.com",
    "linkedin": "https://www.linkedin.com/in/janani-krithika-26b019334",
    "instagram": "https://www.instagram.com/janani.krithika/",
    "description": "Contributing to team outreach and communications",
    "year": "25-26",
    "order": 24,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Bhuvan Prakash",
    "role": "Deputy Manager",
    "subteam": "DevOps",
    "Department": "CSE",
    "photoUrl": null,
    "email": "bhuvanprakash06@gmail.com",
    "linkedin": "https://www.linkedin.com/in/bhuvan-prakash-b20a7a379",
    "instagram": "https://www.instagram.com/bhuvan._prakash/",
    "description": "Supporting DevOps initiatives and technical projects",
    "year": "25-26",
    "order": 25,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Pavithra M A",
    "role": "Deputy Manager",
    "subteam": "Creatives",
    "Department": "ECE",
    "photoUrl": null,
    "email": "pavithra55ma@gmail.com",
    "linkedin": "https://www.linkedin.com/in/pavithra-m-a-b52476324",
    "instagram": "https://www.instagram.com/pavithra_m_a",
    "description": "Designing creative content for team initiatives",
    "year": "25-26",
    "order": 26,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Aryan Nagle",
    "role": "Deputy Manager",
    "subteam": "Corporate Communications",
    "Department": "ICE",
    "photoUrl": null,
    "email": "aryannagle362@gmail.com",
    "linkedin": "https://www.linkedin.com/in/aryan-nagle-a22840343",
    "instagram": "https://www.instagram.com/a_ryann06/",
    "description": "Assisting in corporate communications and events",
    "year": "25-26",
    "order": 27,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Bhuvaneswaran B R",
    "role": "Deputy Manager",
    "subteam": "Creatives",
    "Department": "MME",
    "photoUrl": null,
    "email": "bhuvaneswaranbr@gmail.com",
    "linkedin": "https://www.linkedin.com/in/bhuvaneswaran-b-r-7b5725322",
    "instagram": "https://www.instagram.com/i__am_bhuvi02",
    "description": "Creating visuals for team projects and events",
    "year": "25-26",
    "order": 28,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Nandhana V",
    "role": "Deputy Manager",
    "subteam": "Corporate Communications",
    "Department": "MME",
    "photoUrl": null,
    "email": "nandhanav2006@gmail.com",
    "linkedin": "https://www.linkedin.com/in/nandhana-v-312a81379/",
    "instagram": "https://www.instagram.com/_nandhana_v/",
    "description": "Supporting team communication strategies",
    "year": "25-26",
    "order": 29,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Vishal Durai",
    "role": "Deputy Manager",
    "subteam": "Corporate Communications",
    "Department": "MME",
    "photoUrl": null,
    "email": "vishaldurai06@gmail.com",
    "linkedin": "https://www.linkedin.com/in/vishal-d-7ab937312",
    "instagram": "https://www.instagram.com/_._vizhal_._",
    "description": "Contributing to team outreach efforts",
    "year": "25-26",
    "order": 30,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Vaidya Nilay Vivek",
    "role": "Deputy Manager",
    "subteam": "Corporate Communications",
    "Department": "EEE",
    "photoUrl": null,
    "email": "nilayvaidya2005@gmail.com",
    "linkedin": "https://www.linkedin.com/in/nilay-vaidya-051993333",
    "instagram": "https://www.instagram.com/nilay0341",
    "description": "Supporting team outreach and communications",
    "year": "25-26",
    "order": 31,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Muhesh Alagappan Thiyagarajan",
    "role": "Deputy Manager",
    "subteam": "Creatives",
    "Department": "EEE",
    "photoUrl": null,
    "email": "muheshat416@gmail.com",
    "linkedin": "https://www.linkedin.com/in/muhesh-a-t-39b0aa354/",
    "instagram": "https://www.instagram.com/mu.he.sh/",
    "description": "Crafting creative designs for team initiatives",
    "year": "25-26",
    "order": 32,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Lakshana S",
    "role": "Deputy Manager",
    "subteam": "Corporate Communications",
    "Department": "EEE",
    "photoUrl": null,
    "email": "lakshana4486@gmail.com",
    "linkedin": "https://www.linkedin.com/in/lakshana-s-aa437a326/",
    "instagram": "https://www.instagram.com/lakshana2848",
    "description": "Assisting in team communication efforts",
    "year": "25-26",
    "order": 33,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Priyanshu Mahajan",
    "role": "Deputy Manager",
    "subteam": "Corporate Communications",
    "Department": "ICE",
    "photoUrl": null,
    "email": "priyanshumahajan6@gmail.com",
    "linkedin": "https://www.linkedin.com/in/priyanshu-mahajan-102a14379",
    "instagram": "https://www.instagram.com/priyanshu.mahajan_",
    "description": "Contributing to corporate communications",
    "year": "25-26",
    "order": 34,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Jatin Suresh Subramani",
    "role": "Deputy Manager",
    "subteam": "Creatives",
    "Department": "ARCH",
    "photoUrl": null,
    "email": "jatinsuresh5647@gmail.com",
    "linkedin": "https://www.linkedin.com/in/jatin-suresh-a732bb309",
    "instagram": "https://www.instagram.com/scient_nitt/",
    "description": "Designing visuals for team projects",
    "year": "25-26",
    "order": 35,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Poluru Saketh Koundinya",
    "role": "Deputy Manager",
    "subteam": "DevOps",
    "Department": "CSE",
    "photoUrl": null,
    "email": "polurusaketh@gmail.com",
    "linkedin": "https://www.linkedin.com/in/saketh-poluru-515b91315",
    "instagram": "https://www.instagram.com/granger__47",
    "description": "Supporting DevOps and technical development",
    "year": "25-26",
    "order": 36,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Samarth Pattewar",
    "role": "Deputy Manager",
    "subteam": "Corporate Communications",
    "Department": "ICE",
    "photoUrl": null,
    "email": "samarthbpattewar@gmail.com",
    "linkedin": "https://www.linkedin.com/in/samarth-pattewar-64191034a",
    "instagram": "https://www.instagram.com/psam_arth",
    "description": "Assisting in team outreach and communications",
    "year": "25-26",
    "order": 37,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Muhammad Yousuf",
    "role": "Deputy Manager",
    "subteam": "Creatives",
    "Department": "ARCH",
    "photoUrl": null,
    "email": "muhammadyousuf5winners@gmail.com",
    "linkedin": "https://www.linkedin.com/company/scientnitt/",
    "instagram": "https://www.instagram.com/__you._.suf",
    "description": "Creating engaging visual content",
    "year": "25-26",
    "order": 38,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Meeduri Rithwik Sundar",
    "role": "Deputy Manager",
    "subteam": "Creatives",
    "Department": "ARCH",
    "photoUrl": null,
    "email": "srinivasreddykaripireddy566@gmail.com",
    "linkedin": "https://www.linkedin.com/in/meeduri-rithwik-002172329",
    "instagram": "https://www.instagram.com/scient_nitt/",
    "description": "Contributing to creative design projects",
    "year": "25-26",
    "order": 11,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Jayasri R",
    "role": "Deputy Manager",
    "subteam": "Corporate Communications",
    "Department": "CIVIL",
    "photoUrl": null,
    "email": "jayasrijha2006@gmail.com",
    "linkedin": "https://in.linkedin.com/in/jayasri-rajasundaram-143a4a291",
    "instagram": "https://www.instagram.com/jayasri_jerry22",
    "description": "Supporting corporate communications",
    "year": "25-26",
    "order": 40,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Harshitha R",
    "role": "Deputy Manager",
    "subteam": "Corporate Communications",
    "Department": "CSE",
    "photoUrl": null,
    "email": "harshitharaman123@gmail.com",
    "linkedin": "https://www.linkedin.com/company/scientnitt/",
    "instagram": "https://www.instagram.com/harshey238",
    "description": "Assisting in team communication efforts",
    "year": "25-26",
    "order": 41,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Krishvinraam Mohan",
    "role": "Deputy Manager",
    "subteam": "DevOps",
    "Department": "PROD",
    "photoUrl": null,
    "email": "krishvinraam3@gmail.com",
    "linkedin": "https://www.linkedin.com/in/krishvinraam-mohan-5a82261ab/",
    "instagram": "https://www.instagram.com/krishvin_3_/",
    "description": "Contributing to DevOps and technical projects",
    "year": "25-26",
    "order": 42,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Monashri S",
    "role": "Deputy Manager",
    "subteam": "Creatives",
    "Department": "MME",
    "photoUrl": null,
    "email": "mshrismail@gmail.com",
    "linkedin": "https://www.linkedin.com/in/monashri-s-1b900b37a",
    "instagram": "https://www.instagram.com/monashri_._",
    "description": "Crafting creative visuals for the team",
    "year": "25-26",
    "order": 43,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Swathi Chokalingam",
    "role": "Deputy Manager",
    "subteam": "Corporate Communications",
    "Department": "EEE",
    "photoUrl": null,
    "email": "swathinit2028@gmail.com",
    "linkedin": "https://www.linkedin.com/in/swathi-chokalingam-590b39379",
    "instagram": "https://www.instagram.com/swathi_chok",
    "description": "Supporting team outreach and communications",
    "year": "25-26",
    "order": 44,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Sriya Ghosh",
    "role": "Project Manager",
    "subteam": "Project Management",
    "Department": "MECH",
    "photoUrl": null,
    "email": "sriyaghosh444@gmail.com",
    "linkedin": "https://www.linkedin.com/in/sriya-ghosh-0a93792a3",
    "instagram": "https://www.linkedin.com/company/scientnitt/",
    "description": "Leading project management initiatives",
    "year": "25-26",
    "order": 46,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "D Sai Sri Mouriya",
    "role": "Project Manager",
    "subteam": "Project Management",
    "Department": "EEE",
    "photoUrl": null,
    "email": "saisrimouriyadhava.06@gmail.com",
    "linkedin": "https://www.linkedin.com/in/d-sai-sri-mouriya-1041792a7",
    "instagram": "https://www.linkedin.com/company/scientnitt/",
    "description": "Coordinating project management efforts",
    "year": "25-26",
    "order": 47,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "A Durgesh",
    "role": "Project Manager",
    "subteam": "Project Management",
    "Department": "MECH",
    "photoUrl": null,
    "email": "adurgesh192@gmail.com",
    "linkedin": "https://www.linkedin.com/in/a-durgesh",
    "instagram": "https://www.instagram.com/dark_radar.8816",
    "description": "Driving project management and team coordination",
    "year": "25-26",
    "order": 48,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Aysha Nawreen M",
    "role": "Project Manager",
    "subteam": "Project Management",
    "Department": "CHEM",
    "photoUrl": null,
    "email": "ayshareen005@gmail.com",
    "linkedin": "https://www.linkedin.com/in/aysha-nawreen",
    "instagram": "https://www.instagram.com/aysha.nawreen_",
    "description": "Overseeing project planning and execution",
    "year": "25-26",
    "order": 49,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Hem Sai",
    "role": "Project Manager",
    "subteam": "Project Management",
    "Department": "PROD",
    "photoUrl": null,
    "email": "meh.hem2508@gmail.com",
    "linkedin": "https://www.linkedin.com/in/hem77/",
    "instagram": "https://www.instagram.com/meh_._hem/",
    "description": "Managing project workflows and deliverables",
    "year": "25-26",
    "order": 50,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "S Sundar Palaniappan",
    "role": "Project Manager",
    "subteam": "Project Management",
    "Department": "ICE",
    "photoUrl": null,
    "email": "sundarpalaniappan30@gmail.com",
    "linkedin": "https://www.linkedin.com/in/sundar-palaniappan-s",
    "instagram": "https://www.instagram.com/s_sundar13",
    "description": "Leading project management strategies",
    "year": "25-26",
    "order": 51,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "A M Yafea Nazz",
    "role": "Project Manager",
    "subteam": "Project Management",
    "Department": "MECH",
    "photoUrl": null,
    "email": "amyafeanazz.dc@gmail.com",
    "linkedin": "https://www.linkedin.com/in/a-m-yafea-nazz-990586378",
    "instagram": "https://www.instagram.com/yafeanazz.11",
    "description": "Coordinating project initiatives and timelines",
    "year": "25-26",
    "order": 52,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Ragipalyam Ananda Swaroop",
    "role": "Project Manager",
    "subteam": "Project Management",
    "Department": "CSE",
    "photoUrl": null,
    "email": "anandaswaroop153@gmail.com",
    "linkedin": "https://www.linkedin.com/in/ananda-swaroop-0abbba312/",
    "instagram": "https://www.linkedin.com/company/scientnitt/",
    "description": "Supporting project management and technical coordination",
    "year": "25-26",
    "order": 53,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Fariza Jabeen Z",
    "role": "Project Manager",
    "subteam": "Project Management",
    "Department": "MECH",
    "photoUrl": null,
    "email": "starshiner11roblox@gmail.com",
    "linkedin": "https://www.linkedin.com/me?trk=p_mwlite_feed-secondary_nav",
    "instagram": "https://www.instagram.com/fariza_jabeen/",
    "description": "Managing project planning and team coordination",
    "year": "25-26",
    "order": 55,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Swasthika M",
    "role": "Project Manager",
    "subteam": "Project Management",
    "Department": "MME",
    "photoUrl": null,
    "email": "lizzyben1410@gmail.com",
    "linkedin": "https://in.linkedin.com/in/swasthika-manoharan-392b0831b",
    "instagram": "https://www.instagram.com/butter_14_scotch",
    "description": "Leading project management efforts",
    "year": "25-26",
    "order": 56,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "E Shakthi Ganesh",
    "role": "Project Manager",
    "subteam": "Project Management",
    "Department": "ICE",
    "photoUrl": null,
    "email": "kawaskininja575@gmail.com",
    "linkedin": "https://www.linkedin.com/in/shakthi-ganesh-elavarasan-80b451353",
    "instagram": "https://www.instagram.com/meesg02",
    "description": "Coordinating project execution and deliverables",
    "year": "25-26",
    "order": 57,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Drishya Anil",
    "role": "Manager",
    "subteam": "Creatives",
    "Department": "Design",
    "photoUrl": null,
    "email": "drishyaanil265@gmail.com",
    "linkedin": "",
    "instagram": "",
    "description": "Creating engaging visual content for the team",
    "year": "25-26",
    "order": 19,
    "cardColor": "#facc15",
    "isMock": false
  },

  // ─── 2026-27 Deputy Managers ─────────────────────────────────────────────

  {
    "name": "MUNTHA VENKATA AKASH",
    "role": "Deputy Manager",
    "subteam": "DevOps",
    "Department": "Computer Science Engineering",
    "photoUrl": "",
    "email": "mv.akash08@gmail.com",
    "linkedin": "https://www.linkedin.com/in/venkata-akash?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagram": "https://www.instagram.com/_mv.akash?igsi=bTN3MHo4ZnVlbnA4",
    "description": "",
    "year": "26-27",
    "order": 1,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Vrinda V Nair",
    "role": "Deputy Manager",
    "subteam": "Creatives",
    "Department": "BSc.BEd",
    "photoUrl": "",
    "email": "vrindanair25@gmail.com",
    "linkedin": "https://www.linkedin.com/in/vrinda-nair-b563353b5?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagram": "https://www.instagram.com/vrindaa_v_nair?igsi=MWFvcHFmMTN6andnNg==",
    "description": "",
    "year": "26-27",
    "order": 7,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Nithish Gopal",
    "role": "Deputy Manager",
    "subteam": "Corporate Communications",
    "Department": "Instrumentation and Control Engineering",
    "photoUrl": "",
    "email": "nithishgopal4806@gmail.com",
    "linkedin": "https://www.linkedin.com/in/nithishgopal",
    "instagram": "https://www.instagram.com/nithish_gopal4806",
    "description": "",
    "year": "26-27",
    "order": 13,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Kanishka shri muruganantham",
    "role": "Deputy Manager",
    "subteam": "DevOps",
    "Department": "Electronics and Communication Engineering",
    "photoUrl": "",
    "email": "kanishkashri2007@gmail.com",
    "linkedin": "https://www.linkedin.com/in/kanishka-shri-muruganantham-7015ab349?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagram": "https://www.instagram.com/kanishka._shri?igsi=OHA4azE3eHM4eTRy",
    "description": "",
    "year": "26-27",
    "order": 4,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Sourav Das",
    "role": "Deputy Manager",
    "subteam": "DevOps",
    "Department": "Instrumentation and Control Engineering",
    "photoUrl": "",
    "email": "sd8479104@gmail.com",
    "linkedin": "https://www.linkedin.com/in/sourav-das-914109375/",
    "instagram": "https://www.instagram.com/__sour4v.0_/?hl=en",
    "description": "",
    "year": "26-27",
    "order": 5,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "MallikarjunaNaidu",
    "role": "Deputy Manager",
    "subteam": "DevOps",
    "Department": "Computer Science Engineering",
    "photoUrl": "",
    "email": "mallikarjunanaiduchapana@gmail.com",
    "linkedin": "https://www.linkedin.com/in/mallikarjunanaidu-chapana-485147372?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagram": "https://www.instagram.com/arjunkrishna_00834/",
    "description": "",
    "year": "26-27",
    "order": 2,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Shouhardo Sen",
    "role": "Deputy Manager",
    "subteam": "Corporate Communications",
    "Department": "Electrical and Electronics Engineering",
    "photoUrl": "",
    "email": "senshouhardo@gmail.com",
    "linkedin": "https://www.linkedin.com/in/shouhardo-sen-a386a7432?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagram": "https://www.instagram.com/shouhardopurno?igsi=dTR0MG8wOXp3azBz",
    "description": "",
    "year": "26-27",
    "order": 14,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Anuj Giri Goswami",
    "role": "Deputy Manager",
    "subteam": "DevOps",
    "Department": "Electrical and Electronics Engineering",
    "photoUrl": "",
    "email": "anujgirigoswami56@gmail.com",
    "linkedin": "https://www.linkedin.com/in/anuj-giri-a875a239b?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagram": "https://www.instagram.com/anuj.g4?igsi=MWtrYW5saW02NjJwdA==",
    "description": "",
    "year": "26-27",
    "order": 6,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Sachin kumar",
    "role": "Deputy Manager",
    "subteam": "Creatives",
    "Department": "Mechanical Engineering",
    "photoUrl": "",
    "email": "sachin24122006@gmail.com",
    "linkedin": "https://www.linkedin.com/in/sachin-kumar-b324b3290?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagram": "https://www.instagram.com/sachinkumar751969?igsi=MWpuajczaG0xYzIyaQ==",
    "description": "",
    "year": "26-27",
    "order": 8,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "E Pricilla Jona Christy",
    "role": "Deputy Manager",
    "subteam": "Creatives",
    "Department": "Production Engineering",
    "photoUrl": "",
    "email": "epjc2006@gmail.com",
    "linkedin": "https://www.linkedin.com/in/pricilla-jona-christy-e-2a972437b?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagram": "https://www.instagram.com/115.pricilla?igsi=MXE1eDdrbHNwd2ZsOQ==",
    "description": "",
    "year": "26-27",
    "order": 9,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "DHIVAKAR V",
    "role": "Deputy Manager",
    "subteam": "Corporate Communications",
    "Department": "Production Engineering",
    "photoUrl": "",
    "email": "dhivakar131@gmail.com",
    "linkedin": "https://www.linkedin.com/in/dhivakar-nitt/",
    "instagram": "https://www.instagram.com/itzz_dhivakxr/",
    "description": "",
    "year": "26-27",
    "order": 15,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Deekshanyaa Kalaivanan",
    "role": "Deputy Manager",
    "subteam": "Creatives",
    "Department": "BSc.BEd",
    "photoUrl": "",
    "email": "deekshanyaakalaivanan@gmail.com",
    "linkedin": "https://www.linkedin.com/in/deekshanyaa-kalaivanan-b184403ba?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagram": "https://www.instagram.com/yaashan_yaps?igsi=djFkemF2eXgyZ3F3",
    "description": "",
    "year": "26-27",
    "order": 10,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Kavinraj G",
    "role": "Deputy Manager",
    "subteam": "Corporate Communications",
    "Department": "Instrumentation and Control Engineering",
    "photoUrl": "",
    "email": "kavinrajsgn@gmail.com",
    "linkedin": "https://www.linkedin.com/in/kavinraj-g-771867432",
    "instagram": "https://www.instagram.com/kavinraj555?igsi=cGpoYWw4aHI2dXk4",
    "description": "",
    "year": "26-27",
    "order": 16,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Keerthana S Nair",
    "role": "Deputy Manager",
    "subteam": "Corporate Communications",
    "Department": "Chemical Engineering",
    "photoUrl": "",
    "email": "keerthananair.2006@gmail.com",
    "linkedin": "https://www.linkedin.com/in/keerthana-nair-b38310381/",
    "instagram": "https://www.instagram.com/hello.keerth?igsi=MWxlMmtteWU1bjRrNg==",
    "description": "",
    "year": "26-27",
    "order": 17,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Arpit Anand Sharma",
    "role": "Deputy Manager",
    "subteam": "Corporate Communications",
    "Department": "Civil Engineering",
    "photoUrl": "",
    "email": "arpitsharma.mun@gmail.com",
    "linkedin": "https://www.linkedin.com/in/arpit-anand-sharma/",
    "instagram": "https://www.instagram.com/the_arpit_sharma__/",
    "description": "",
    "year": "26-27",
    "order": 18,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "kimberly",
    "role": "Deputy Manager",
    "subteam": "Creatives",
    "Department": "Production Engineering",
    "photoUrl": "",
    "email": "srinivasreddykaripireddy566@gmail.com",
    "linkedin": "",
    "instagram": "https://www.instagram.com/eatshoe_?igsi=ZW94dWx5cjJud21z&utm_source=qr",
    "description": "",
    "year": "26-27",
    "order": 11,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Eniyan Govindharajan",
    "role": "Deputy Manager",
    "subteam": "Corporate Communications",
    "Department": "Civil Engineering",
    "photoUrl": "",
    "email": "eniyangovindharajan@gmail.com",
    "linkedin": "https://www.linkedin.com/in/eniyan-govindharajan-a7618636a?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagram": "https://www.instagram.com/eniyan_7?igsi=MXZ2azd2ZGFjMWJzcA==",
    "description": "",
    "year": "26-27",
    "order": 19,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Sarves V Y",
    "role": "Deputy Manager",
    "subteam": "Corporate Communications",
    "Department": "Metallurgical and Materials Engineering",
    "photoUrl": "",
    "email": "sarvasav7@gmail.com",
    "linkedin": "https://www.linkedin.com/in/sarves-v-y-550421398",
    "instagram": "https://www.instagram.com/sarvesvy/",
    "description": "",
    "year": "26-27",
    "order": 20,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Vaibhav Sinha",
    "role": "Deputy Manager",
    "subteam": "Creatives",
    "Department": "Instrumentation and Control Engineering",
    "photoUrl": "",
    "email": "906sainikschoolambikapur@gmail.com",
    "linkedin": "https://in.linkedin.com/in/vaibhav-sinha-739179355",
    "instagram": "https://www.instagram.com/vaibhav._.1209?igsi=MTQxcG56MDVwd3RidA%3D%3D&utm_source=qr",
    "description": "",
    "year": "26-27",
    "order": 12,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Anukarsh Singh",
    "role": "Deputy Manager",
    "subteam": "Corporate Communications",
    "Department": "Production Engineering",
    "photoUrl": "",
    "email": "anukarsh.nitt@gmail.com",
    "linkedin": "https://www.linkedin.com/in/anukarshsingh?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
    "instagram": "https://www.instagram.com/anukarshhhh",
    "description": "",
    "year": "26-27",
    "order": 21,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Krishithaa B S",
    "role": "Deputy Manager",
    "subteam": "DevOps",
    "Department": "Computer Science Engineering",
    "photoUrl": "",
    "email": "krishithaabs@gmail.com",
    "linkedin": "https://in.linkedin.com/in/krishithaa-bs",
    "instagram": "https://www.instagram.com/krishithaa_23/",
    "description": "",
    "year": "26-27",
    "order": 3,
    "cardColor": "#facc15",
    "isMock": false
  },

  // ─── 2026-27 Core ────────────────────────────────────────────────────────
  {
    "name": "D Sai Sri Mouriya",
    "role": "Core",
    "subteam": "Cores",
    "Department": "Electrical and Electronics Engineering",
    "photoUrl": "",
    "email": "saisrimouriyadhava.06@gmail.com",
    "linkedin": "https://www.linkedin.com/in/d-sai-sri-mouriya",
    "instagram": "https://www.instagram.com/sai_sri_mouriya",
    "description": "",
    "year": "26-27",
    "order": 22,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Advaith S",
    "role": "Core",
    "subteam": "Cores",
    "Department": "Computer Science Engineering",
    "photoUrl": "",
    "email": "advaith.t20@gmail.com",
    "linkedin": "https://www.linkedin.com/in/advaiths006/",
    "instagram": "https://www.instagram.com/advaith.fyi/",
    "description": "",
    "year": "26-27",
    "order": 23,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Pranesh S K",
    "role": "Core",
    "subteam": "Cores",
    "Department": "Metallurgical and Materials Engineering",
    "photoUrl": "",
    "email": "pranesh26erd@gmail.com",
    "linkedin": "https://www.linkedin.com/in/pranesh-s-k-b647082a4/",
    "instagram": "https://www.instagram.com/pranesh.kamalakannan/",
    "description": "",
    "year": "26-27",
    "order": 24,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "A M Yafea Nazz",
    "role": "Core",
    "subteam": "Cores",
    "Department": "Mechanical Engineering",
    "photoUrl": "",
    "email": "amyafeanazz.nitt@gmail.com",
    "linkedin": "https://www.linkedin.com/in/a-m-yafea-nazz-990586378",
    "instagram": "https://www.instagram.com/yafeaaa?igsi=Mmx3d3F4NG03dTkw",
    "description": "",
    "year": "26-27",
    "order": 25,
    "cardColor": "#facc15",
    "isMock": false
  },

  // ─── 2026-27 Managers (Corporate Communications, Creatives, DevOps) ─────
  {
    "name": "Nandhana V",
    "role": "Manager",
    "subteam": "Corporate Communications",
    "Department": "Metallurgical and Materials Engineering",
    "photoUrl": "",
    "email": "nandhanav2006@gmail.com",
    "linkedin": "https://www.linkedin.com/in/nandhana-v-312a81379/",
    "instagram": "https://www.instagram.com/_nandhana_v/",
    "description": "",
    "year": "26-27",
    "order": 28,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "S. Janani Krithika",
    "role": "Manager",
    "subteam": "Corporate Communications",
    "Department": "Civil Engineering",
    "photoUrl": "",
    "email": "janani.krithika2006@gmail.com",
    "linkedin": "https://www.linkedin.com/in/janani-krithika-26b019334?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagram": "https://www.instagram.com/s_j_k25?igsi=cnVvczRtaHViNDBt",
    "description": "",
    "year": "26-27",
    "order": 29,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Pravar Surana",
    "role": "Manager",
    "subteam": "Corporate Communications",
    "Department": "Instrumentation and Control Engineering",
    "photoUrl": "",
    "email": "pravarsurana1604@gmail.com",
    "linkedin": "https://www.linkedin.com/in/pravar-surana-a477283aa?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagram": "https://www.instagram.com/pravar_1645?igsi=bzI1YTF4dnloZjM4",
    "description": "",
    "year": "26-27",
    "order": 30,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Bhuvaneswaran B R",
    "role": "Manager",
    "subteam": "Creatives",
    "Department": "Metallurgical and Materials Engineering",
    "photoUrl": "",
    "email": "bhuvaneswaranbr@gmail.com",
    "linkedin": "https://www.linkedin.com/in/bhuvaneswaran-b-r-7b5725322?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagram": "https://www.instagram.com/i__am_bhuvi02?igsi=NjN0d20xN2oyN2Vv",
    "description": "",
    "year": "26-27",
    "order": 31,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Muhesh Alagappan Thiyagarajan",
    "role": "Manager",
    "subteam": "Creatives",
    "Department": "Electrical and Electronics Engineering",
    "photoUrl": "",
    "email": "muheshat416@gmail.com",
    "linkedin": "https://in.linkedin.com/in/muhesh-a-t-39b0aa354",
    "instagram": "https://www.instagram.com/mu.he.sh?igsi=MWN1ZnE2dDJ1ZDczYg==",
    "description": "",
    "year": "26-27",
    "order": 32,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Kamalakannan R",
    "role": "Manager",
    "subteam": "Corporate Communications",
    "Department": "Civil Engineering",
    "photoUrl": "",
    "email": "kamalakannanravichandran@gmail.com",
    "linkedin": "https://www.linkedin.com/in/kamalakannan-ravichandran-843b662a5?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagram": "https://www.instagram.com/kamalakannanravichandran11/",
    "description": "",
    "year": "26-27",
    "order": 33,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Aryan Nagle",
    "role": "Manager",
    "subteam": "Corporate Communications",
    "Department": "Instrumentation and Control Engineering",
    "photoUrl": "",
    "email": "aryannagle362@gmail.com",
    "linkedin": "https://www.linkedin.com/in/aryan-nagle-a22840343?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagram": "https://www.instagram.com/a_ryann06?igsi=cXF4NnNyNXU3djdm",
    "description": "",
    "year": "26-27",
    "order": 34,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Chebrolu Bhuvan",
    "role": "Manager",
    "subteam": "DevOps",
    "Department": "Computer Science Engineering",
    "photoUrl": "",
    "email": "bhuvanchebrolu@gmail.com",
    "linkedin": "https://www.linkedin.com/in/bhuvan-chebrolu-5835641b2",
    "instagram": "https://www.instagram.com/bhuvaneshwar2966/",
    "description": "",
    "year": "26-27",
    "order": 35,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Nayan Vamsi",
    "role": "Manager",
    "subteam": "DevOps",
    "Department": "Computer Science Engineering",
    "photoUrl": "",
    "email": "nayanvamsi@gmail.com",
    "linkedin": "https://www.linkedin.com/in/nayan-vamsi-sunkarapalli-b2a93536b",
    "instagram": "https://www.instagram.com/___nayan__007",
    "description": "",
    "year": "26-27",
    "order": 36,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Bhuvan Prakash",
    "role": "Manager",
    "subteam": "DevOps",
    "Department": "Computer Science Engineering",
    "photoUrl": "",
    "email": "bhuvtosh@gmail.com",
    "linkedin": "https://www.linkedin.com/in/bhuvan-prakash-b20a7a379",
    "instagram": "https://www.instagram.com/bhuvan._prakash",
    "description": "",
    "year": "26-27",
    "order": 37,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Priyanshu Mahajan",
    "role": "Manager",
    "subteam": "Corporate Communications",
    "Department": "Instrumentation and Control Engineering",
    "photoUrl": "",
    "email": "priyanshumahajan6@gmail.com",
    "linkedin": "https://www.linkedin.com/in/priyanshu-mahajan-102a14379?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagram": "https://www.instagram.com/priyanshu.mahajan_?igsi=ajlnOGV3NWo3YnYw",
    "description": "",
    "year": "26-27",
    "order": 38,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "SANSKAR SHARMA",
    "role": "Manager",
    "subteam": "DevOps",
    "Department": "Computer Science Engineering",
    "photoUrl": "",
    "email": "sharmasanskar7201@gmail.com",
    "linkedin": "https://www.linkedin.com/in/sanskarnitt/",
    "instagram": "https://www.instagram.com/sanskar.nitt/",
    "description": "",
    "year": "26-27",
    "order": 39,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Rithwik sundar",
    "role": "Manager",
    "subteam": "Creatives",
    "Department": "Architecture",
    "photoUrl": "",
    "email": "nikithabhukya00@gmail.com",
    "linkedin": "https://www.linkedin.com/in/rithwik-sundar-meeduri-002172329?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
    "instagram": "https://www.instagram.com/_w1.k1?utm_source=qr",
    "description": "",
    "year": "26-27",
    "order": 40,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Pattewar Samarth Balaji",
    "role": "Manager",
    "subteam": "Corporate Communications",
    "Department": "Instrumentation and Control Engineering",
    "photoUrl": "",
    "email": "samarthbpattewar@gmail.com",
    "linkedin": "https://www.linkedin.com/in/samarth-pattewar-64191034a?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagram": "https://www.instagram.com/psam_arth?igsi=d3Y4NWwxOG05ZHZx",
    "description": "",
    "year": "26-27",
    "order": 41,
    "cardColor": "#facc15",
    "isMock": false
  },

  // ─── 2026-27 Senior Managers (2025-26 Managers) ─────────────────────────
  {
    "name": "Dendukuri Soumya",
    "role": "Senior Manager",
    "subteam": "Corporate Communications",
    "Department": "CIVIL",
    "photoUrl": null,
    "email": "soumya95507@gmail.com",
    "linkedin": "https://www.linkedin.com/company/scientnitt/",
    "instagram": "https://www.instagram.com/scient_nitt/",
    "description": "Coordinating corporate communications and outreach",
    "year": "26-27",
    "order": 8,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Divyansh Kumar Agrawal",
    "role": "Senior Manager",
    "subteam": "DevOps",
    "Department": "CSE",
    "photoUrl": null,
    "email": "divyanshkumaragrawal80@gmail.com",
    "linkedin": "https://www.linkedin.com/in/divyansh-agrawal-4a806a2b1",
    "instagram": "https://www.instagram.com/divyansh_agr_80",
    "description": "Driving DevOps solutions and technical development",
    "year": "26-27",
    "order": 9,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Gargi Gupta",
    "role": "Senior Manager",
    "subteam": "Corporate Communications",
    "Department": "MECH",
    "photoUrl": null,
    "email": "gargi.gupta0601@gmail.com",
    "linkedin": "https://www.linkedin.com/company/scientnitt/",
    "instagram": "https://www.instagram.com/scient_nitt/",
    "description": "Managing corporate communications and events",
    "year": "26-27",
    "order": 10,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Indhumathi V",
    "role": "Senior Manager",
    "subteam": "DevOps",
    "Department": "PROD",
    "photoUrl": null,
    "email": "indhu23.v@gmail.com",
    "linkedin": "https://www.linkedin.com/company/scientnitt/",
    "instagram": "https://www.instagram.com/scient_nitt/",
    "description": "Enhancing team outreach through communications",
    "year": "26-27",
    "order": 11,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Kakularam Saiprakash Reddy",
    "role": "Senior Manager",
    "subteam": "DevOps",
    "Department": "CIVIL",
    "photoUrl": null,
    "email": "kakularamsaiprakashreddy9@gmail.com",
    "linkedin": "https://www.linkedin.com/in/sai-prakash-reddy-kakularam-323273280/",
    "instagram": "https://www.instagram.com/saiprakashreddy.k/",
    "description": "Contributing to DevOps and technical innovation",
    "year": "26-27",
    "order": 12,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Mona M S",
    "role": "Senior Manager",
    "subteam": "Corporate Communications",
    "Department": "MME",
    "photoUrl": null,
    "email": "mona.shivakkumar@gmail.com",
    "linkedin": "https://www.linkedin.com/in/mona-m-s-10228b300",
    "instagram": "https://www.instagram.com/_.mona._.01._/",
    "description": "Leading corporate communication strategies",
    "year": "26-27",
    "order": 13,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Shivam Mishra",
    "role": "Senior Manager",
    "subteam": "DevOps",
    "Department": "ICE",
    "photoUrl": null,
    "email": "realshivat2606@gmail.com",
    "linkedin": "https://www.linkedin.com/company/scientnitt/",
    "instagram": "https://www.instagram.com/scient_nitt/",
    "description": "Supporting DevOps projects and technical tasks",
    "year": "26-27",
    "order": 15,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Tanisha Narasimman",
    "role": "Senior Manager",
    "subteam": "Corporate Communications",
    "Department": "MME",
    "photoUrl": null,
    "email": "tanishanarasimman777@gmail.com",
    "linkedin": "https://www.linkedin.com/company/scientnitt/",
    "instagram": "https://www.instagram.com/scient_nitt/",
    "description": "Promoting team initiatives through communications",
    "year": "26-27",
    "order": 16,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Vedavarshini",
    "role": "Senior Manager",
    "subteam": "Creatives",
    "Department": "EEE",
    "photoUrl": null,
    "email": "vedavarshiniv2@gmail.com",
    "linkedin": "https://www.linkedin.com/company/scientnitt/",
    "instagram": "https://www.instagram.com/scient_nitt/",
    "description": "Crafting creative visuals for team projects",
    "year": "26-27",
    "order": 17,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Thejashvee",
    "role": "Senior Manager",
    "subteam": "Corporate Communications",
    "Department": "ICE",
    "photoUrl": null,
    "email": "thejubabu1@gmail.com",
    "linkedin": "https://www.linkedin.com/company/scientnitt/",
    "instagram": "https://www.instagram.com/scient_nitt/",
    "description": "Enhancing team visibility through communications",
    "year": "26-27",
    "order": 18,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Drishya Anil",
    "role": "Senior Manager",
    "subteam": "Creatives",
    "Department": "Design",
    "photoUrl": null,
    "email": "drishyaanil265@gmail.com",
    "linkedin": "",
    "instagram": "",
    "description": "Creating engaging visual content for the team",
    "year": "26-27",
    "order": 19,
    "cardColor": "#facc15",
    "isMock": false
  },

  // ─── 2026-27 Managers (Project Management) ──────────────────────────────
  {
    "name": "A DURGESH",
    "role": "Manager",
    "subteam": "Project Management",
    "Department": "Mechanical Engineering",
    "photoUrl": "",
    "email": "adurgesh192@gmail.com",
    "linkedin": "https://www.linkedin.com/in/a-durgesh",
    "instagram": "https://www.instagram.com/dark_radar.8816/",
    "description": "",
    "year": "26-27",
    "order": 26,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Dhetsshanya N",
    "role": "Manager",
    "subteam": "Project Management",
    "Department": "Chemical Engineering",
    "photoUrl": "",
    "email": "dhetsshanya@gmail.com",
    "linkedin": "https://www.linkedin.com/in/dhetsshanyanarendran",
    "instagram": "https://www.instagram.com/dhetsshanya/",
    "description": "",
    "year": "26-27",
    "order": 27,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Athena Nath",
    "role": "Manager",
    "subteam": "Project Management",
    "Department": "Metallurgical and Materials Engineering",
    "photoUrl": "",
    "email": "sumidebnath1983@gmail.com",
    "linkedin": "https://www.linkedin.com/in/athena-nath-203308331",
    "instagram": "https://www.instagram.com/anehta.a",
    "description": "",
    "year": "26-27",
    "order": 42,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Prathikshaa Vangal Santosh",
    "role": "Manager",
    "subteam": "Project Management",
    "Department": "Production Engineering",
    "photoUrl": "",
    "email": "prathikshaakrr@gmail.com",
    "linkedin": "https://www.linkedin.com/in/prathikshaa-vangal-santosh-338709340?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagram": "https://www.instagram.com/prathikshaa1724?igsi=bjF2N3EydW1seHhn",
    "description": "",
    "year": "26-27",
    "order": 43,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Gangiti Neeraj",
    "role": "Manager",
    "subteam": "Project Management",
    "Department": "Instrumentation and Control Engineering",
    "photoUrl": "",
    "email": "gangitineeraj@gmail.com",
    "linkedin": "https://www.linkedin.com/in/gangiti-neeraj-5b7551390?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagram": "https://www.instagram.com/neeraj_gangiti/?hl=en",
    "description": "",
    "year": "26-27",
    "order": 44,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Bala Guru Prasaad B",
    "role": "Manager",
    "subteam": "Project Management",
    "Department": "Mechanical Engineering",
    "photoUrl": "",
    "email": "kt.balaguruprasaad@gmail.com",
    "linkedin": "https://www.linkedin.com/in/bala-guru-prasaad-b-517b7031b?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagram": "https://www.instagram.com/bala_guru_prasaad?utm_source=qr&igsi=cnNOb2dOaTdlNWUx",
    "description": "",
    "year": "26-27",
    "order": 45,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Aadhith Dharmaraj",
    "role": "Manager",
    "subteam": "Project Management",
    "Department": "Instrumentation and Control Engineering",
    "photoUrl": "",
    "email": "aadhith.dharmaraj@gmail.com",
    "linkedin": "https://www.linkedin.com/in/aadhith-dharmaraj-24748b332/",
    "instagram": "https://www.instagram.com/aadhith181",
    "description": "",
    "year": "26-27",
    "order": 46,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "M Manurajan",
    "role": "Manager",
    "subteam": "Project Management",
    "Department": "Electrical and Electronics Engineering",
    "photoUrl": "",
    "email": "manurajan6337@gmail.com",
    "linkedin": "https://www.linkedin.com/in/manurajan-m-67374a383?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagram": "https://www.instagram.com/manurajan_2807?igsi=NnMzN3h0dGM1ZGE0",
    "description": "",
    "year": "26-27",
    "order": 47,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "Varshini Dhamodaran",
    "role": "Manager",
    "subteam": "Project Management",
    "Department": "Mechanical Engineering",
    "photoUrl": "",
    "email": "varshinidhamodaran6@gmail.com",
    "linkedin": "https://www.linkedin.com/in/varshini-dhamodaran",
    "instagram": "",
    "description": "",
    "year": "26-27",
    "order": 48,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "T Vidush",
    "role": "Manager",
    "subteam": "Project Management",
    "Department": "Electrical and Electronics Engineering",
    "photoUrl": "",
    "email": "vidushin06@gmail.com",
    "linkedin": "",
    "instagram": "https://www.instagram.com/vidzee_06/",
    "description": "",
    "year": "26-27",
    "order": 49,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "V Rupesh Kumar",
    "role": "Manager",
    "subteam": "Project Management",
    "Department": "Chemical Engineering",
    "photoUrl": "",
    "email": "rupeshforce@gmail.com",
    "linkedin": "https://www.linkedin.com/in/v-rupesh-kumar-38a031434/",
    "instagram": "",
    "description": "",
    "year": "26-27",
    "order": 50,
    "cardColor": "#facc15",
    "isMock": false
  },
  {
    "name": "B THUVARAKESH",
    "role": "Manager",
    "subteam": "Project Management",
    "Department": "Mechanical Engineering",
    "photoUrl": "",
    "email": "thuvara1504@gmail.com",
    "linkedin": "https://www.linkedin.com/in/thuvarakesh-balamuralikrishnan-661552328",
    "instagram": "https://www.instagram.com/thuvarakesh_15_/",
    "description": "",
    "year": "26-27",
    "order": 51,
    "cardColor": "#facc15",
    "isMock": false
  }
];

async function seedTeamMembers() {
  try {
    await connectDB();
    console.log('Starting idempotent seed of ' + realTeamMembers.length + ' team members...');

    let createdCount = 0;
    let updatedCount = 0;

    for (const member of realTeamMembers) {
      const filter = {
        name: member.name,
        role: member.role,
        year: member.year
      };

      const existing = await TeamMember.findOne(filter);
      await TeamMember.findOneAndUpdate(
        filter,
        { $set: member },
        { upsert: true, new: true, runValidators: true }
      );

      if (existing) {
        updatedCount++;
      } else {
        createdCount++;
      }
    }

    console.log('\n✅ Seeding complete!');
    console.log('   - Created: ' + createdCount);
    console.log('   - Updated: ' + updatedCount);
    const totalCount = await TeamMember.countDocuments();
    console.log('   - Total TeamMembers in DB: ' + totalCount + '\n');

  } catch (err) {
    console.error('❌ Error seeding team members:', err.message);
    process.exitCode = 1;
  } finally {
    if (mongoose.connection.readyState !== 0) {
      await mongoose.disconnect();
      console.log('Disconnected from MongoDB.');
    }
  }
}

if (require.main === module) {
  seedTeamMembers();
}

module.exports = {
  realTeamMembers,
  seedTeamMembers
};
